import { EditorView } from '@codemirror/view';
import { JSDOM } from 'jsdom';
const html=await Bun.file('./src/web/index.html').text();
const dom=new JSDOM(html,{url:'http://localhost/s/test/',pretendToBeVisual:true,runScripts:'outside-only'});
const w=dom.window;
for(const key of ['window','document','navigator','Node','NodeFilter','Element','HTMLElement','HTMLInputElement','HTMLTextAreaElement','HTMLDivElement','HTMLButtonElement','DocumentFragment','MutationObserver','DOMParser','getComputedStyle','Event','KeyboardEvent','MouseEvent','Range','ShadowRoot','SVGElement','location','history']) (globalThis as any)[key]=key==='window'?w:(w as any)[key];
for(const key of ['requestAnimationFrame','cancelAnimationFrame','addEventListener','removeEventListener']) (globalThis as any)[key]=(w as any)[key].bind(w);
(globalThis as any).ResizeObserver=class{observe(){} unobserve(){} disconnect(){}};
(globalThis as any).IntersectionObserver=class{observe(){} unobserve(){} disconnect(){}};
(w as any).matchMedia=()=>({matches:true,addEventListener(){},removeEventListener(){}});
Object.defineProperty(w.document,'fonts',{value:{ready:Promise.resolve(),addEventListener(){},removeEventListener(){}}});
(w.navigator as any).sendBeacon=()=>true;
Range.prototype.getBoundingClientRect=()=>({left:0,right:0,top:0,bottom:0,width:0,height:0} as DOMRect);
Range.prototype.getClientRects=()=>[] as any;
let doc={path:'/tmp/workflow.md',body:'---\ntitle: Test\n---\n\n# Heading\r\n\n[Guide](guide.md) and `code`.\n\nA \\$100 stock costs **only** \\$3.\n\n- list\n',bodyRevision:'sha256:original',ledgerRevision:'empty',annotations:{threads:[]}};
let preferences={theme:'tether',customThemes:[],uiScale:1,commentTextSize:16};
const writes:string[]=[];
(globalThis as any).fetch=async(url:string,options:any={})=>{
 const path=new URL(url,w.location.href).pathname;
 if(path.endsWith('/bootstrap'))return Response.json({document:doc,preferences,capabilities:{},scroll:0,zoom:100});
 if(path.endsWith('/preferences'))return Response.json(preferences);
 if(path.endsWith('/lease'))return Response.json({path:doc.path,bodyRevision:doc.bodyRevision,ledgerRevision:doc.ledgerRevision});
 if(path.endsWith('/file')){if(options.method==='PUT'){const request=JSON.parse(options.body);if(request.expectedBodyRevision!==doc.bodyRevision)return Response.json({error:{message:'Conflict'}},{status:409});writes.push(request.content);doc={...doc,body:request.content,bodyRevision:'sha256:'+writes.length};}return Response.json(doc);}
 if(path.endsWith('/annotations'))return Response.json({...doc,annotations:{threads:[]}});
 if(path.endsWith('/draft')||path.endsWith('/position'))return Response.json({});
 return Response.json({});
};
const build=await Bun.build({entrypoints:['./src/web/app.ts'],target:'browser',format:'iife'});
if(!build.success)throw new Error(String(build.logs));
(w as any).fetch=globalThis.fetch;
(w as any).structuredClone=structuredClone;
(w as any).TextEncoder=TextEncoder;
(w as any).TextDecoder=TextDecoder;
(w as any).ResizeObserver=(globalThis as any).ResizeObserver;
(w as any).IntersectionObserver=(globalThis as any).IntersectionObserver;
w.eval(await build.outputs.find(x=>x.path.endsWith('.js'))!.text());
const wait=async(check:()=>boolean)=>{for(let i=0;i<500;i++){if(check())return;await Bun.sleep(20);}throw new Error('Timed out: '+document.querySelector('#notice')?.textContent);};
await wait(()=>!!document.querySelector('.ProseMirror')&&!(document.querySelector('#editor') as HTMLElement)?.inert);
// Same-document navigation scrolls without resetting the host tab's URL state.
let scrolled = false;
const heading = document.querySelector<HTMLElement>('#heading')!;
heading.scrollIntoView = () => { scrolled = true; };
const anchorLink = document.createElement('a');
anchorLink.href = '#heading';
document.querySelector('#editor')!.append(anchorLink);
const beforeUrl = w.location.href;
anchorLink.click();
anchorLink.remove();
if (!scrolled || w.location.href !== beforeUrl) throw new Error('Heading link failed to scroll without navigating');
(document.querySelector('#source') as HTMLButtonElement).click();
await wait(()=>!!document.querySelector('.wm-source-editor'));
const input=EditorView.findFromDOM(document.querySelector('.wm-source-editor')!)!;
if(input.state.sliceDoc()!==doc.body||writes.length)throw new Error('Opening source rewrote bytes');
const sourceSpans=[...input.contentDOM.querySelectorAll('span')];
for(const token of ['#','**','guide.md','`']) {
 if(!sourceSpans.some(span=>span.textContent===token&&span.className))throw new Error('Missing source color: '+token);
}
if(sourceSpans.some(span=>span.textContent==='Heading'||span.textContent==='only'))throw new Error('Source coloring styled ordinary prose');
const originalSource=input.state.sliceDoc();
input.dispatch({changes:{from:input.state.doc.length,insert:'\nSource edit with \\$42.\n'}});
const changedSource=input.state.sliceDoc();
input.contentDOM.dispatchEvent(new w.KeyboardEvent('keydown',{key:'z',code:'KeyZ',ctrlKey:true,bubbles:true,cancelable:true}));
if(input.state.sliceDoc()!==originalSource)throw new Error('Source undo failed');
input.contentDOM.dispatchEvent(new w.KeyboardEvent('keydown',{key:'y',code:'KeyY',ctrlKey:true,bubbles:true,cancelable:true}));
if(input.state.sliceDoc()!==changedSource)throw new Error('Source redo failed');
await wait(()=>writes.length===1);
if(writes[0]!==input.state.sliceDoc())throw new Error('Source save normalized the body');
(document.querySelector('#source') as HTMLButtonElement).click();
await wait(()=>!document.querySelector('.wm-source-editor'));
if(writes.length!==1)throw new Error('Returning to reader rewrote source');
// Accepting every external change preserves its source formatting byte-for-byte.
const external='## Updated heading\n\nA \\$5 **price**.\n\n| a | b |\n|---|---|\n| 1 | 2 |\n';
doc={...doc,body:external,bodyRevision:'sha256:external'};
w.dispatchEvent(new w.Event('pageshow'));
await wait(()=>!document.querySelector<HTMLButtonElement>('#save-review')!.hidden);
(document.querySelector('#save-review') as HTMLButtonElement).click();
await wait(()=>writes.length===2);
if(writes[1]!==external)throw new Error('Accept All rewrote external formatting: '+JSON.stringify({actual:writes[1],external}));
await wait(()=>document.querySelector<HTMLElement>('#conflict')!.hidden);
(document.querySelector('#source') as HTMLButtonElement).click();
await wait(()=>!!document.querySelector('.wm-source-editor'));
const conflictedSource=EditorView.findFromDOM(document.querySelector('.wm-source-editor')!)!;
doc={...doc,body:'Newer disk content\n',bodyRevision:'sha256:newer'};
conflictedSource.dispatch({changes:{from:conflictedSource.state.doc.length,insert:'Unsaved local change'}});
await wait(()=>!document.querySelector<HTMLElement>('#conflict')!.hidden);
if(Number(writes.length)!==2||!conflictedSource.state.sliceDoc().endsWith('Unsaved local change'))throw new Error('Source conflict lost a draft or overwrote disk');
console.log('Reader workflows passed: exact source saves, byte-preserving Accept All, and source conflicts.');
w.dispatchEvent(new w.Event('pagehide'));dom.window.close();
