import assert from "node:assert/strict";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { chromium, webkit, type Page } from "playwright";
import { startSettingsStage } from "./settings-stage";

const directory = await mkdtemp(join(tmpdir(), "tether-settings-stage-check-"));
const feedbackFile = join(directory, "feedback.json");
const stage = await startSettingsStage({ port: 0, feedbackFile });
async function annotate(page: Page, target: string, note: string, send = true) {
  await page.getByRole("button", { name: "Start feedback mode", exact: true }).click();
  await page.locator(target).click();
  await page.locator("[data-annotation-popup] textarea").fill(note);
  await page.getByRole("button", { name: "Add", exact: true }).click();
  if (send) {
    await page.getByRole("button", { name: "Send Annotations", exact: true }).click();
    await page.getByText(/^Saved \d+ notes across \d+ pages for your agent\.$/).waitFor();
  }
  await page.getByRole("button", { name: "Exit", exact: true }).click();
}
try {
  for (const engine of [chromium, webkit]) {
    const browser = await engine.launch();
    try {
      const context = await browser.newContext({ viewport: { width: 1100, height: 900 } });
      const page = await context.newPage();
      const errors: string[] = []; page.on("pageerror", error => errors.push(error.message));
      page.on("dialog", dialog => void dialog.accept());
      await page.goto(stage.url);
      await page.getByRole("button", { name: "Set up Tether Fly", exact: true }).click();
      await page.waitForURL("**/#fly/setup/hub");
      assert.equal(context.pages().length, 1, "Setup must stay in the Settings tab");
      await page.getByLabel("Which computer should be Tether’s hub?").fill("Staging Mac");
      await annotate(page, "#fly-settings h4", "Hub question feedback", false);
      await page.getByRole("button", { name: "Next", exact: true }).click();
      await page.waitForURL("**/#fly/setup/access");
      await annotate(page, "#fly-settings h4", "Access question feedback");
      assert.equal(JSON.parse(await readFile(feedbackFile, "utf8"))["/fresh/settings/#fly/setup/hub"].annotations[0].comment, "Hub question feedback", "Send must include saved annotations from other pages");
      await rm(feedbackFile);
      await page.reload();
      await page.getByText("Saved 2 notes across 2 pages for your agent.", { exact: true }).waitFor();
      assert.equal(JSON.parse(await readFile(feedbackFile, "utf8"))["/fresh/settings/#fly/setup/hub"].annotations[0].comment, "Hub question feedback", "Reload must import existing browser annotations");
      await page.getByText("Step 2 of 5", { exact: true }).waitFor();
      await page.goBack();
      await page.getByText("Step 1 of 5", { exact: true }).waitFor();
      assert.equal(await page.getByLabel("Which computer should be Tether’s hub?").inputValue(), "Staging Mac");
      await page.goForward();
      await page.getByText("Step 2 of 5", { exact: true }).waitFor();
      await page.getByRole("button", { name: "Next", exact: true }).click();
      await page.getByLabel("New machine name").fill("Staging server");
      await page.getByRole("button", { name: "Next", exact: true }).click();
      await page.getByRole("button", { name: "Next", exact: true }).click();
      await page.getByLabel("Allow browser access from outside your private network?").selectOption("true");
      await page.getByRole("button", { name: "Prepare setup", exact: true }).click();
      await page.waitForURL("**/fresh/setup/agent/");
      await page.getByRole("button", { name: "Change answers" }).click();
      await page.getByLabel("Which computer should be Tether’s hub?").fill("Edited hub");
      await page.reload();
      assert.equal(await page.getByLabel("Which computer should be Tether’s hub?").inputValue(), "Edited hub");
      await page.getByRole("button", { name: "Cancel", exact: true }).click();
      await page.getByRole("button", { name: "Run simulated installation" }).click();
      await page.getByText("Approve the setup agent’s progress reports first.", { exact: true }).waitFor();
      await page.getByRole("button", { name: /^Allow progress reports/ }).click();
      await page.getByText(/Agent report \(unverified\): Ready to install/).waitFor();
      await page.getByRole("button", { name: "Run simulated installation" }).click();
      await page.waitForURL("**/fresh/setup/sign-in/");
      await annotate(page, "#settings-dialog h3:visible", "Sign-in feedback");
      await page.getByRole("button", { name: "Simulate passkey sign-in" }).click();
      await page.waitForURL("**/fresh/setup/verify/");
      await page.getByRole("button", { name: "Verify setup", exact: true }).click();
      await page.locator("#fly-feedback").filter({ hasText: "confirm" }).waitFor();
      await page.getByLabel("I verified the native sidebar", { exact: false }).check();
      await page.getByLabel("I verified access from a browser", { exact: false }).check();
      await page.getByRole("button", { name: "Verify setup", exact: true }).click();
      await page.waitForURL("**/fresh/setup/complete/");
      await page.getByText("Completed setup", { exact: true }).click();
      await page.getByRole("heading", { name: "Setup verified" }).waitFor();
      const feedback = JSON.parse(await readFile(feedbackFile, "utf8"));
      assert.equal(feedback["/fresh/settings/#fly/setup/hub"].annotations[0].comment, "Hub question feedback");
      assert.equal(feedback["/fresh/settings/#fly/setup/access"].annotations.length, 1, "Steps must have independent annotations");
      assert.equal(feedback["/fresh/setup/sign-in/"].annotations[0].comment, "Sign-in feedback");
      await page.getByRole("button", { name: "Reset to fresh install" }).click();
      await page.waitForURL("**/fresh/settings/");
      await page.getByRole("button", { name: "Set up Tether Fly", exact: true }).waitFor();
      assert.deepEqual(Object.keys(JSON.parse(await readFile(feedbackFile, "utf8"))), Object.keys(feedback), "Reset must keep submitted feedback");
      await page.getByRole("button", { name: "Set up Tether Fly", exact: true }).click();
      await page.getByRole("button", { name: "Next", exact: true }).click();
      await page.getByLabel("Where will you use Tether?").selectOption("browser");
      await page.getByRole("button", { name: "Next", exact: true }).click();
      await page.getByText("Step 3 of 3", { exact: true }).waitFor();
      await page.getByRole("button", { name: "Prepare setup", exact: true }).click();
      await page.waitForURL("**/fresh/setup/agent/");
      await page.getByRole("button", { name: /^Allow progress reports/ }).click();
      await page.getByText(/Agent report \(unverified\): Ready to install/).waitFor();
      await page.getByRole("button", { name: "Run simulated installation" }).click();
      await page.waitForURL("**/fresh/setup/sign-in/");
      await page.getByRole("button", { name: "Simulate passkey sign-in" }).click();
      await page.waitForURL("**/fresh/setup/verify/");
      await page.getByRole("button", { name: "Verify setup", exact: true }).click();
      await page.waitForURL("**/fresh/setup/complete/");
      await page.getByRole("link", { name: "Existing setup", exact: true }).click();
      await page.getByText("File machines (3)", { exact: true }).click();
      await page.getByText("Hub controls", { exact: true }).click();
      await page.getByRole("button", { name: "Disable Tether Fly…", exact: true }).click();
      await page.getByRole("button", { name: "Disable this machine and relocate Tether to a different one" }).click();
      await page.getByLabel("Which computer should be Tether’s hub?").fill("Relocated hub");
      await page.reload();
      assert.equal(await page.getByLabel("Which computer should be Tether’s hub?").inputValue(), "Relocated hub");
      await page.getByRole("button", { name: "Cancel", exact: true }).click();
      await page.getByText("File machines (3)", { exact: true }).click();
      await page.getByRole("row", { name: /Travel laptop Offline Path only/ }).waitFor();
      assert.equal(await page.getByLabel("Machine name", { exact: true }).count(), 0);
      await page.getByRole("button", { name: "Edit Mac", exact: true }).click();
      await page.getByLabel("Machine name", { exact: true }).first().fill("Renamed Mac");
      await page.getByRole("button", { name: "Save machine", exact: true }).first().click();
      await page.getByText("Machine saved.", { exact: true }).waitFor();
      await page.getByRole("row", { name: /Renamed Mac Available Path only/ }).waitFor();
      assert.equal(await page.getByLabel("Machine name", { exact: true }).count(), 0);
      await page.getByRole("button", { name: "Edit phoenix-bot", exact: true }).click();
      await page.getByLabel("Machine name", { exact: true }).fill("Discard this edit");
      await page.getByRole("button", { name: "Cancel", exact: true }).click();
      await page.getByRole("row", { name: /phoenix-bot Available Machine \+ path/ }).waitFor();
      await page.getByText("Browsers and other clients (3)", { exact: true }).click();
      await page.getByText(/Safari on iPhone/).waitFor();
      await page.getByRole("button", { name: "Sign out", exact: true }).click();
      await page.waitForURL("**/existing/setup/sign-in/");
      await page.getByRole("button", { name: "Simulate passkey sign-in" }).click();
      await page.waitForURL("**/existing/settings/");
      await page.getByText("File machines (3)", { exact: true }).click();
      await page.setViewportSize({ width: 375, height: 650 });
      assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), "Settings must fit narrow panes");
      assert((await page.getByRole("button", { name: "Edit Renamed Mac", exact: true }).boundingBox())!.height < 40, "Edit labels must stay on one line in narrow panes");
      await page.mouse.move(180, 350); await page.mouse.wheel(0, 800);
      await page.waitForFunction(() => scrollY > 0);
      assert.deepEqual(errors, []);
      await context.close();
    } finally { await browser.close(); }
  }
  assert.equal((await fetch(stage.url + "/fresh/api/stage/reset", { method: "POST", headers: { origin: "https://elsewhere.invalid" }, body: "{}" })).status, 403);
  console.log("Settings staging passed: Chromium/WebKit, same-tab installation, reload/back/forward, independent Agentation feedback, reset, existing machines/clients, narrow scrolling and origin checks.");
} finally { await stage.close(); await rm(directory, { recursive: true, force: true }); }
