import { createHash } from "node:crypto";
import { lstat, mkdir, open, realpath, unlink } from "node:fs/promises";
import { join, resolve } from "node:path";
import type { AnnotationEvent } from "../core/index";
import type { PrivateStore } from "../storage/private-store";

export type ValidatedImportItem = { name: string; body: string; events: AnnotationEvent[] };
export type PackageImportResult = {
  paths: string[];
  completed: Array<{ index: number; path: string; replayed: boolean }>;
  failed: Array<{ index: number; path: string; code: string; message: string; cleanupRequired?: boolean }>;
  outcome: "applied" | "partially_applied" | "not_applied";
  retry: string;
};

// Event IDs are regenerated by validation. Fingerprint the ordered conversation,
// retaining reply relationships without depending on those temporary IDs.
function fingerprint(item: ValidatedImportItem, directory: string): string {
  const ids = new Map(item.events.map((event, index) => [event.id, index]));
  const events = item.events.map(({ id: _id, seq: _seq, ...event }) => ({
    ...event, ...("threadId" in event ? { threadId: ids.get(event.threadId) } : {}),
  }));
  return createHash("sha256").update(JSON.stringify({ directory, name: item.name, body: item.body, events })).digest("hex");
}

/** Validated package items commit independently. Receipts share each item's
 * annotation transaction and let retries recover lost successful responses. */
export async function importPackageItems(
  items: ValidatedImportItem[], directory: string, store: PrivateStore, now: () => number = Date.now,
): Promise<PackageImportResult> {
  await mkdir(resolve(directory), { recursive: true });
  const root = await realpath(resolve(directory));
  store.db.exec(`CREATE TABLE IF NOT EXISTS package_import_receipts (
    fingerprint TEXT PRIMARY KEY, path TEXT NOT NULL, document_id TEXT NOT NULL REFERENCES documents(id) ON DELETE CASCADE, created_at INTEGER NOT NULL
  )`);
  const completed: PackageImportResult["completed"] = [];
  const failed: PackageImportResult["failed"] = [];
  for (const [index, item] of items.entries()) {
    const path = join(root, item.name);
    const key = fingerprint(item, root);
    const prior = store.db.query("SELECT d.path FROM package_import_receipts r JOIN documents d ON d.id=r.document_id WHERE fingerprint=?").get(key) as { path: string } | null;
    if (prior) { completed.push({ index, path: prior.path, replayed: true }); continue; }
    let file: Awaited<ReturnType<typeof open>> | undefined;
    let owned: { ino: number; dev: number; mtimeMs: number; size: number } | undefined;
    let committed = false;
    try {
      if (store.documentForPath(path)) throw Object.assign(new Error("The destination already has a Tether conversation."), { code: "destination_record_exists" });
      file = await open(path, "wx", 0o600);
      owned = await file.stat();
      try { await file.writeFile(item.body, "utf8"); await file.sync(); }
      finally { owned = await file.stat(); }
      const current = await lstat(path);
      if (await realpath(path) !== path || current.ino !== owned.ino || current.dev !== owned.dev || current.mtimeMs !== owned.mtimeMs || current.size !== owned.size) {
        throw Object.assign(new Error("The destination path changed during import."), { code: "destination_changed" });
      }
      store.db.transaction(() => {
        if (store.documentForPath(path)) throw Object.assign(new Error("The destination already has a Tether conversation."), { code: "destination_record_exists" });
        const document = store.ensureDocument(path, now());
        store.replaceEvents(path, item.events, now());
        store.db.query("INSERT INTO package_import_receipts(fingerprint,path,document_id,created_at) VALUES (?,?,?,?)")
          .run(key, path, document.id, now());
      }).immediate();
      committed = true;
      completed.push({ index, path, replayed: false });
    } catch (cause) {
      let cleanupRequired = false;
      if (owned && !committed) {
        try {
          const current = await lstat(path);
          if (current.ino === owned.ino && current.dev === owned.dev && current.mtimeMs === owned.mtimeMs && current.size === owned.size) await unlink(path);
          else cleanupRequired = true;
        } catch (cleanup) { cleanupRequired = (cleanup as NodeJS.ErrnoException).code !== "ENOENT"; }
      }
      const code = typeof (cause as { code?: unknown })?.code === "string" ? (cause as { code: string }).code : "package_item_failed";
      failed.push({ index, path, code, message: cause instanceof Error ? cause.message : String(cause), ...(cleanupRequired ? { cleanupRequired } : {}) });
    } finally { await file?.close().catch(() => {}); }
  }
  return {
    paths: completed.map(({ path }) => path), completed, failed,
    outcome: failed.length ? (completed.length ? "partially_applied" : "not_applied") : "applied",
    retry: "Fix failed destinations and repeat the same package and directory. Completed items are retained and skipped, even if later edited or removed.",
  };
}
